SELECT_CATEGORY = 1
SELECT_ROOM = 2
SELECT_DAY = 3
SELECT_DEVICE_COMBO = 4
SELECT_TIME = 5
SELECT_DEVICE = 6
CONFIRM_BOOKING = 7
SELECT_DURATION = 8

SELECT_PC_TYPE = 9

ADMIN_BLOCK_ROOM = 10
ADMIN_BLOCK_DEVICE = 11
ADMIN_BLOCK_REASON = 12

ADMIN_UNBLOCK_DEVICE = 13

ADMIN_ADD_ADMIN = 14
